# Use an official Node.js runtime as a parent image
FROM node:14-alpine as build

# Set the working directory to /app
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application files to the container
COPY . .

# Build the Angular app
RUN npm run build --prod

# Use an official Nginx runtime as a parent image
FROM nginx:1.21.3-alpine

# Copy the nginx configuration file to the container
COPY ./.nginx/nginx.conf /etc/nginx/nginx.conf

# Copy the built Angular app to the Nginx document root
COPY --from=build /app/dist/chat-ai-improvements /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
