# syntax=docker/dockerfile:1.4

FROM --platform=$BUILDPLATFORM node:lts-bullseye-slim as builder

RUN mkdir /project
WORKDIR /project

RUN npm install -g @angular/cli@15

COPY package.json package-lock.json ./

RUN npm ci

VOLUME [ "/project" ]

COPY . .

CMD ["ng", "serve", "--host", "0.0.0.0"]