# Use an official Node.js runtime as a parent image
FROM node:14-alpine

RUN mkdir /app
WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

VOLUME [ "/app" ]

# Copy the rest of the application code to the container
COPY . .

# Expose port 3000 to the outside world
EXPOSE 3000

# Start the application in development mode
CMD ["npm", "run", "dev"]
