# Use an official Node.js runtime as a parent image
FROM node:14-alpine

RUN mkdir /app
WORKDIR /app

RUN npm install -g strong-pm

COPY package.json package-lock.json ./

RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Expose port 3000 to the outside world
EXPOSE 3000

# Start the application in development mode
CMD ["slc", "start"]
